import "./Service.deploy";
import "./Directory.deploy";
import "./ProposalGateway.deploy";
import "./ERC20Mock.deploy";
import "./addUniswapLiquidity";
import "./addUniswapTestnet";
import "./whitelistTokens";
import "./WhitelistedTokens.deploy";
import "./Metadata.deploy";
